/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PethreonInterface extends ethers.utils.Interface {
  functions: {
    "cancelPledge(address)": FunctionFragment;
    "createPledge(address,uint256,uint256)": FunctionFragment;
    "deposit()": FunctionFragment;
    "getContractBalance()": FunctionFragment;
    "getContributorBalance()": FunctionFragment;
    "getCreatorBalance()": FunctionFragment;
    "myPledgeTo(address)": FunctionFragment;
    "withdrawAsContributor(uint256)": FunctionFragment;
    "withdrawAsCreator()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cancelPledge",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createPledge",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "myPledgeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawAsContributor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAsCreator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelPledge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPledge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "myPledgeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAsContributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAsCreator",
    data: BytesLike
  ): Result;

  events: {
    "ContributorDeposited(uint256,address,uint256)": EventFragment;
    "ContributorWithdrew(uint256,address,uint256)": EventFragment;
    "CreatorWithdrew(uint256,address,uint256)": EventFragment;
    "PledgeCancelled(uint256,address,address)": EventFragment;
    "PledgeCreated(uint256,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContributorDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributorWithdrew"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatorWithdrew"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PledgeCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PledgeCreated"): EventFragment;
}

export class Pethreon extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PethreonInterface;

  functions: {
    cancelPledge(
      _creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "cancelPledge(address)"(
      _creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createPledge(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createPledge(address,uint256,uint256)"(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deposit()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getContractBalance(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    "getContractBalance()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    getContributorBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getContributorBalance()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCreatorBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "getCreatorBalance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    myPledgeTo(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        weiPerPeriod: BigNumber;
        afterLastPeriod: BigNumber;
      }
    >;

    "myPledgeTo(address)"(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        weiPerPeriod: BigNumber;
        afterLastPeriod: BigNumber;
      }
    >;

    withdrawAsContributor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawAsContributor(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawAsCreator(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawAsCreator()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  cancelPledge(
    _creator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "cancelPledge(address)"(
    _creator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createPledge(
    _creator: string,
    _weiPerPeriod: BigNumberish,
    _periods: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createPledge(address,uint256,uint256)"(
    _creator: string,
    _weiPerPeriod: BigNumberish,
    _periods: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deposit()"(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getContractBalance(overrides?: CallOverrides): Promise<BigNumber>;

  "getContractBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

  getContributorBalance(overrides?: CallOverrides): Promise<BigNumber>;

  "getContributorBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCreatorBalance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "getCreatorBalance()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  myPledgeTo(
    _creator: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      weiPerPeriod: BigNumber;
      afterLastPeriod: BigNumber;
    }
  >;

  "myPledgeTo(address)"(
    _creator: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      weiPerPeriod: BigNumber;
      afterLastPeriod: BigNumber;
    }
  >;

  withdrawAsContributor(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawAsContributor(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawAsCreator(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawAsCreator()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancelPledge(_creator: string, overrides?: CallOverrides): Promise<void>;

    "cancelPledge(address)"(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createPledge(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createPledge(address,uint256,uint256)"(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(overrides?: CallOverrides): Promise<BigNumber>;

    "deposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    getContractBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getContractBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getContributorBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getContributorBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatorBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getCreatorBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    myPledgeTo(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        weiPerPeriod: BigNumber;
        afterLastPeriod: BigNumber;
      }
    >;

    "myPledgeTo(address)"(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        weiPerPeriod: BigNumber;
        afterLastPeriod: BigNumber;
      }
    >;

    withdrawAsContributor(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawAsContributor(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAsCreator(overrides?: CallOverrides): Promise<void>;

    "withdrawAsCreator()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    ContributorDeposited(
      period: null,
      contributor: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { period: BigNumber; contributor: string; amount: BigNumber }
    >;

    ContributorWithdrew(
      period: null,
      contributor: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { period: BigNumber; contributor: string; amount: BigNumber }
    >;

    CreatorWithdrew(
      period: null,
      creator: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { period: BigNumber; creator: string; amount: BigNumber }
    >;

    PledgeCancelled(
      period: null,
      creator: null,
      contributor: null
    ): TypedEventFilter<
      [BigNumber, string, string],
      { period: BigNumber; creator: string; contributor: string }
    >;

    PledgeCreated(
      period: null,
      creator: null,
      contributor: null,
      weiPerPeriod: null,
      periods: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber],
      {
        period: BigNumber;
        creator: string;
        contributor: string;
        weiPerPeriod: BigNumber;
        periods: BigNumber;
      }
    >;
  };

  estimateGas: {
    cancelPledge(
      _creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "cancelPledge(address)"(
      _creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createPledge(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createPledge(address,uint256,uint256)"(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deposit()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getContractBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getContractBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getContributorBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getContributorBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatorBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "getCreatorBalance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    myPledgeTo(_creator: string, overrides?: CallOverrides): Promise<BigNumber>;

    "myPledgeTo(address)"(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawAsContributor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawAsContributor(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawAsCreator(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawAsCreator()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelPledge(
      _creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "cancelPledge(address)"(
      _creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createPledge(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createPledge(address,uint256,uint256)"(
      _creator: string,
      _weiPerPeriod: BigNumberish,
      _periods: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deposit()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getContractBalance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getContractBalance()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContributorBalance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getContributorBalance()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreatorBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "getCreatorBalance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    myPledgeTo(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "myPledgeTo(address)"(
      _creator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawAsContributor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawAsContributor(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAsCreator(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawAsCreator()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
