/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Pethreon {
  export type PledgeStruct = {
    creatorAddress: PromiseOrValue<string>;
    contributorAddress: PromiseOrValue<string>;
    weiPerPeriod: PromiseOrValue<BigNumberish>;
    duration: PromiseOrValue<BigNumberish>;
    dateCreated: PromiseOrValue<BigNumberish>;
    periodExpires: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type PledgeStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    creatorAddress: string;
    contributorAddress: string;
    weiPerPeriod: BigNumber;
    duration: BigNumber;
    dateCreated: BigNumber;
    periodExpires: BigNumber;
    status: number;
  };
}

export interface PethreonInterface extends utils.Interface {
  functions: {
    "cancelPledge(address)": FunctionFragment;
    "contributorWithdraw(uint256)": FunctionFragment;
    "createPledge(address,uint256,uint256)": FunctionFragment;
    "creatorWithdraw()": FunctionFragment;
    "currentPeriod()": FunctionFragment;
    "deposit()": FunctionFragment;
    "getContributorBalanceInWei()": FunctionFragment;
    "getContributorPledges()": FunctionFragment;
    "getCreatorBalanceInWei()": FunctionFragment;
    "getCreatorPledges()": FunctionFragment;
    "getExpiredPledges()": FunctionFragment;
    "startOfEpoch()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancelPledge"
      | "contributorWithdraw"
      | "createPledge"
      | "creatorWithdraw"
      | "currentPeriod"
      | "deposit"
      | "getContributorBalanceInWei"
      | "getContributorPledges"
      | "getCreatorBalanceInWei"
      | "getCreatorPledges"
      | "getExpiredPledges"
      | "startOfEpoch"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancelPledge",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorWithdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createPledge",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getContributorBalanceInWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorPledges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorBalanceInWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorPledges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpiredPledges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startOfEpoch",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelPledge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPledge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContributorBalanceInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorPledges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorBalanceInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorPledges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpiredPledges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startOfEpoch",
    data: BytesLike
  ): Result;

  events: {
    "ContributorDeposited(uint256)": EventFragment;
    "ContributorWithdrew(uint256,address,uint256)": EventFragment;
    "CreatorWithdrew(uint256,address,uint256)": EventFragment;
    "PledgeCancelled(uint256,address,address)": EventFragment;
    "PledgeCreated(uint256,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContributorDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributorWithdrew"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatorWithdrew"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PledgeCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PledgeCreated"): EventFragment;
}

export interface ContributorDepositedEventObject {
  newBalance: BigNumber;
}
export type ContributorDepositedEvent = TypedEvent<
  [BigNumber],
  ContributorDepositedEventObject
>;

export type ContributorDepositedEventFilter =
  TypedEventFilter<ContributorDepositedEvent>;

export interface ContributorWithdrewEventObject {
  period: BigNumber;
  contributor: string;
  amount: BigNumber;
}
export type ContributorWithdrewEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  ContributorWithdrewEventObject
>;

export type ContributorWithdrewEventFilter =
  TypedEventFilter<ContributorWithdrewEvent>;

export interface CreatorWithdrewEventObject {
  period: BigNumber;
  creatorAddress: string;
  amount: BigNumber;
}
export type CreatorWithdrewEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  CreatorWithdrewEventObject
>;

export type CreatorWithdrewEventFilter = TypedEventFilter<CreatorWithdrewEvent>;

export interface PledgeCancelledEventObject {
  period: BigNumber;
  creatorAddress: string;
  contributor: string;
}
export type PledgeCancelledEvent = TypedEvent<
  [BigNumber, string, string],
  PledgeCancelledEventObject
>;

export type PledgeCancelledEventFilter = TypedEventFilter<PledgeCancelledEvent>;

export interface PledgeCreatedEventObject {
  period: BigNumber;
  creatorAddress: string;
  contributor: string;
  weiPerPeriod: BigNumber;
  periods: BigNumber;
}
export type PledgeCreatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber],
  PledgeCreatedEventObject
>;

export type PledgeCreatedEventFilter = TypedEventFilter<PledgeCreatedEvent>;

export interface Pethreon extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PethreonInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancelPledge(
      _creatorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    contributorWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createPledge(
      _creatorAddress: PromiseOrValue<string>,
      _weiPerPeriod: PromiseOrValue<BigNumberish>,
      _periods: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    creatorWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentPeriod(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { periodNumber: BigNumber }>;

    deposit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getContributorBalanceInWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    getContributorPledges(
      overrides?: CallOverrides
    ): Promise<
      [Pethreon.PledgeStructOutput[]] & {
        allPledges: Pethreon.PledgeStructOutput[];
      }
    >;

    getCreatorBalanceInWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCreatorPledges(
      overrides?: CallOverrides
    ): Promise<
      [Pethreon.PledgeStructOutput[]] & {
        allPledges: Pethreon.PledgeStructOutput[];
      }
    >;

    getExpiredPledges(
      overrides?: CallOverrides
    ): Promise<
      [Pethreon.PledgeStructOutput[]] & {
        allPledges: Pethreon.PledgeStructOutput[];
      }
    >;

    startOfEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  cancelPledge(
    _creatorAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  contributorWithdraw(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createPledge(
    _creatorAddress: PromiseOrValue<string>,
    _weiPerPeriod: PromiseOrValue<BigNumberish>,
    _periods: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  creatorWithdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  deposit(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getContributorBalanceInWei(overrides?: CallOverrides): Promise<BigNumber>;

  getContributorPledges(
    overrides?: CallOverrides
  ): Promise<Pethreon.PledgeStructOutput[]>;

  getCreatorBalanceInWei(overrides?: CallOverrides): Promise<BigNumber>;

  getCreatorPledges(
    overrides?: CallOverrides
  ): Promise<Pethreon.PledgeStructOutput[]>;

  getExpiredPledges(
    overrides?: CallOverrides
  ): Promise<Pethreon.PledgeStructOutput[]>;

  startOfEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    cancelPledge(
      _creatorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    contributorWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createPledge(
      _creatorAddress: PromiseOrValue<string>,
      _weiPerPeriod: PromiseOrValue<BigNumberish>,
      _periods: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    creatorWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    currentPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(overrides?: CallOverrides): Promise<BigNumber>;

    getContributorBalanceInWei(overrides?: CallOverrides): Promise<BigNumber>;

    getContributorPledges(
      overrides?: CallOverrides
    ): Promise<Pethreon.PledgeStructOutput[]>;

    getCreatorBalanceInWei(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatorPledges(
      overrides?: CallOverrides
    ): Promise<Pethreon.PledgeStructOutput[]>;

    getExpiredPledges(
      overrides?: CallOverrides
    ): Promise<Pethreon.PledgeStructOutput[]>;

    startOfEpoch(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "ContributorDeposited(uint256)"(
      newBalance?: PromiseOrValue<BigNumberish> | null
    ): ContributorDepositedEventFilter;
    ContributorDeposited(
      newBalance?: PromiseOrValue<BigNumberish> | null
    ): ContributorDepositedEventFilter;

    "ContributorWithdrew(uint256,address,uint256)"(
      period?: null,
      contributor?: null,
      amount?: null
    ): ContributorWithdrewEventFilter;
    ContributorWithdrew(
      period?: null,
      contributor?: null,
      amount?: null
    ): ContributorWithdrewEventFilter;

    "CreatorWithdrew(uint256,address,uint256)"(
      period?: null,
      creatorAddress?: null,
      amount?: null
    ): CreatorWithdrewEventFilter;
    CreatorWithdrew(
      period?: null,
      creatorAddress?: null,
      amount?: null
    ): CreatorWithdrewEventFilter;

    "PledgeCancelled(uint256,address,address)"(
      period?: null,
      creatorAddress?: null,
      contributor?: null
    ): PledgeCancelledEventFilter;
    PledgeCancelled(
      period?: null,
      creatorAddress?: null,
      contributor?: null
    ): PledgeCancelledEventFilter;

    "PledgeCreated(uint256,address,address,uint256,uint256)"(
      period?: null,
      creatorAddress?: null,
      contributor?: null,
      weiPerPeriod?: null,
      periods?: null
    ): PledgeCreatedEventFilter;
    PledgeCreated(
      period?: null,
      creatorAddress?: null,
      contributor?: null,
      weiPerPeriod?: null,
      periods?: null
    ): PledgeCreatedEventFilter;
  };

  estimateGas: {
    cancelPledge(
      _creatorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    contributorWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createPledge(
      _creatorAddress: PromiseOrValue<string>,
      _weiPerPeriod: PromiseOrValue<BigNumberish>,
      _periods: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    creatorWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getContributorBalanceInWei(overrides?: CallOverrides): Promise<BigNumber>;

    getContributorPledges(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatorBalanceInWei(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatorPledges(overrides?: CallOverrides): Promise<BigNumber>;

    getExpiredPledges(overrides?: CallOverrides): Promise<BigNumber>;

    startOfEpoch(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cancelPledge(
      _creatorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    contributorWithdraw(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createPledge(
      _creatorAddress: PromiseOrValue<string>,
      _weiPerPeriod: PromiseOrValue<BigNumberish>,
      _periods: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    creatorWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getContributorBalanceInWei(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContributorPledges(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreatorBalanceInWei(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreatorPledges(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getExpiredPledges(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startOfEpoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
