/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Pethreon } from "./Pethreon";

export { Pethreon__factory } from "./factories/Pethreon__factory";
